# Generated by Django 3.2.3 on 2021-06-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.CharField(max_length=200, primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
