# Generated by Django 3.2.3 on 2021-06-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegenre',
            name='name',
            field=models.TextField(),
        ),
    ]
