# Generated by Django 3.2.3 on 2021-06-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_moviegenre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegenre',
            name='id',
            field=models.IntegerField(primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
