# Generated by Django 3.2.3 on 2021-06-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_auto_20210605_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieGenre',
        ),
    ]
