# Generated by Django 3.2.3 on 2021-06-05 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_moviegenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.CharField(max_length=300)),
                ('overview', models.TextField()),
                ('popularity', models.IntegerField()),
                ('tagline', models.TextField()),
                ('title', models.CharField(max_length=300)),
                ('vote_average', models.IntegerField()),
                ('vote_count', models.IntegerField()),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.moviegenre')),
            ],
        ),
    ]
