# Generated by Django 3.2.3 on 2021-06-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_auto_20210605_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.TextField(verbose_name='Original_title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(verbose_name='Overview'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.TextField(verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
