# Generated by Django 3.2.3 on 2021-06-05 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0010_auto_20210605_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.moviegenre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_count',
            field=models.FloatField(blank=True),
        ),
    ]
