# Generated by Django 3.2.3 on 2021-06-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0013_movielist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieList',
        ),
    ]
