# Generated by Django 3.2.3 on 2021-06-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0017_alter_movielist_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.DeleteModel(
            name='MovieList',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
    ]
