# Generated by Django 3.2.3 on 2021-06-08 07:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieapp', '0023_auto_20210608_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('genres', multiselectfield.db.fields.MultiSelectField(choices=[{'Animation': 'Animation', 'id': 16}, {'Comdey': 'Comedy', 'id': 35}, {'Family': 'Family', 'id': 10751}, {'Romance': 'Romance', 'id': 10749}, {'Crime': 'Crime', 'id': 80}, {'Drama': 'Drama', 'id': 18}, {'Action': 'Action', 'id': 28}, {'Thriller': 'Thriller', 'id': 53}, {'Mystery': 'Mystery', 'id': 9648}, {'War': 'War', 'id': 10752}, {'Adventure': 'Adventure', 'id': 12}, {'History': 'History', 'id': 36}, {'Foreign': 'Foreign', 'id': 10769}, {'Horror': 'Horror', 'id': 27}, {'Documentary': 'Documentary', 'id': 99}, {'Music': 'Music', 'id': 10402}, {'Science Fiction': 'Science Fiction', 'id': 878}, {'TV Movie': 'TV Movie', 'id': 10770}, {'Western': 'Western', 'id': 37}, {'Fantasy': 'Fantasy', 'id': 14}], max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5)])),
                ('movieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.movielist')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userId', 'movieId')},
                'index_together': {('userId', 'movieId')},
            },
        ),
    ]
