# Generated by Django 3.2.3 on 2021-06-09 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0027_popularmovies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopularMovies',
        ),
    ]
