# Generated by Django 3.2.3 on 2021-06-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0037_delete_popularmovies'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PopularMovie',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('original_title', models.CharField(max_length=200)),
                ('popularity', models.FloatField()),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('genres', models.ManyToManyField(to='movieapp.MovieGenre')),
            ],
        ),
    ]
