# Generated by Django 3.2.3 on 2021-06-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0038_moviegenre_popularmovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularmovie',
            name='original_title',
        ),
        migrations.RemoveField(
            model_name='popularmovie',
            name='popularity',
        ),
    ]
