# Generated by Django 3.2.3 on 2021-06-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0039_auto_20210609_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopularMovie',
        ),
    ]
