# Generated by Django 3.2.3 on 2021-06-10 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0041_popularmovies'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=None,
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='rating',
            name='movieId',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='userId',
        ),
        migrations.DeleteModel(
            name='MovieList',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
