# Generated by Django 3.2.3 on 2021-06-10 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0044_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.movielist'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='popularmovie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.popularmovies'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
