# Generated by Django 3.2.3 on 2021-06-11 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0046_comment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviegenre',
            old_name='name',
            new_name='genres',
        ),
    ]
