# Generated by Django 3.2.3 on 2021-06-11 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0050_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.moviegenre')),
            ],
        ),
    ]
