# Generated by Django 3.2.3 on 2021-06-11 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0051_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
