# Generated by Django 3.2.3 on 2021-06-13 16:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0053_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genres',
            field=multiselectfield.db.fields.MultiSelectField(choices=[{'Animation': 'Animation', 'id': 16}, {'Comedy': 'Comedy', 'id': 35}, {'Family': 'Family', 'id': 10751}, {'Romance': 'Romance', 'id': 10749}, {'Crime': 'Crime', 'id': 80}, {'Drama': 'Drama', 'id': 18}, {'Action': 'Action', 'id': 28}, {'Thriller': 'Thriller', 'id': 53}, {'Mystery': 'Mystery', 'id': 9648}, {'War': 'War', 'id': 10752}, {'Adventure': 'Adventure', 'id': 12}, {'History': 'History', 'id': 36}, {'Foreign': 'Foreign', 'id': 10769}, {'Horror': 'Horror', 'id': 27}, {'Documentary': 'Documentary', 'id': 99}, {'Music': 'Music', 'id': 10402}, {'Science Fiction': 'Science Fiction', 'id': 878}, {'TV Movie': 'TV Movie', 'id': 10770}, {'Western': 'Western', 'id': 37}, {'Fantasy': 'Fantasy', 'id': 14}], max_length=20),
        ),
    ]
