# Generated by Django 3.2.3 on 2021-06-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0056_alter_genre_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genres',
            field=models.IntegerField(),
        ),
    ]
