# Generated by Django 3.2.3 on 2021-06-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0057_alter_genre_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='id',
        ),
        migrations.AlterField(
            model_name='genre',
            name='genres',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
