# Generated by Django 3.2.3 on 2021-06-13 17:02

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('movieapp', '0058_auto_20210613_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genres',
            new_name='genre',
        ),
    ]
