# Generated by Django 3.2.3 on 2021-06-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0061_alter_genre_genres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
