# Generated by Django 3.2.3 on 2021-06-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0062_delete_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
