# Generated by Django 3.2.3 on 2021-06-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
   

    dependencies = [
        ('movieapp', '0063_delete_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('genres', models.CharField(blank='True', max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('genres', models.CharField(blank=True, max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('genres', models.CharField(blank='True', max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comedy',
            fields=[
                ('genres', models.CharField(blank='True', max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('genres', models.CharField(blank='True', max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documentary',
            fields=[
                ('genres', models.CharField(blank=True, max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('genres', models.CharField(blank='True', max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('genres', models.CharField(blank='True', max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fantasy',
            fields=[
                ('genres', models.CharField(blank=True, max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foreign',
            fields=[
                ('genres', models.CharField(blank=True, max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('genres', models.CharField(blank=True, max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horror',
            fields=[
                ('genres', models.CharField(blank=True, max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('genres', models.CharField(blank=True, max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mystery',
            fields=[
                ('genres', models.CharField(blank='True', max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Romance',
            fields=[
                ('genres', models.CharField(blank='True', max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScienceFiction',
            fields=[
                ('genres', models.CharField(blank=True, max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thriller',
            fields=[
                ('genres', models.CharField(blank='True', max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVMovie',
            fields=[
                ('genres', models.CharField(blank=True, max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('genres', models.CharField(blank='True', max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Western',
            fields=[
                ('genres', models.CharField(blank=True, max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.AlterIndexTogether(
            name='like',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='like',
            name='popularmovie',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=None,
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='rating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='popularmovie',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AlterField(
            model_name='movielist',
            name='genres',
            field=models.CharField(blank='True', max_length=300),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
