# Generated by Django 3.2.3 on 2021-06-14 12:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieapp', '0064_auto_20210614_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5)])),
                ('action', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.action')),
                ('adventure', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.adventure')),
                ('animation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.animation')),
                ('comedy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.comedy')),
                ('crime', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.crime')),
                ('documentary', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.documentary')),
                ('drama', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.drama')),
                ('family', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.family')),
                ('fantasy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.fantasy')),
                ('foreign', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.foreign')),
                ('history', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.history')),
                ('horror', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.horror')),
                ('movie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.movielist')),
                ('music', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.music')),
                ('mystery', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.mystery')),
                ('popularmovies', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.popularmovies')),
                ('romance', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.romance')),
                ('sciencefiction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.sciencefiction')),
                ('thriller', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.thriller')),
                ('tvmovie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.tvmovie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('war', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.war')),
                ('western', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.western')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(max_length=30)),
                ('action', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.action')),
                ('adventure', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.adventure')),
                ('animation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.animation')),
                ('comedy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.comedy')),
                ('crime', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.crime')),
                ('documentary', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.documentary')),
                ('drama', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.drama')),
                ('family', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.family')),
                ('fantasy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.fantasy')),
                ('foreign', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.foreign')),
                ('history', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.history')),
                ('horror', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.horror')),
                ('movie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.movielist')),
                ('music', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.music')),
                ('mystery', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.mystery')),
                ('popularmovies', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.popularmovies')),
                ('romance', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.romance')),
                ('sciencefiction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.sciencefiction')),
                ('thriller', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.thriller')),
                ('tvmovie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.tvmovie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('war', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.war')),
                ('western', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.western')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.action')),
                ('adventure', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.adventure')),
                ('animation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.animation')),
                ('comedy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.comedy')),
                ('crime', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.crime')),
                ('documentary', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.documentary')),
                ('drama', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.drama')),
                ('family', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.family')),
                ('fantasy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.fantasy')),
                ('foreign', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.foreign')),
                ('history', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.history')),
                ('horror', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.horror')),
                ('movie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.movielist')),
                ('music', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.music')),
                ('mystery', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.mystery')),
                ('popularmovies', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.popularmovies')),
                ('romance', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.romance')),
                ('sciencefiction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.sciencefiction')),
                ('thriller', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.thriller')),
                ('tvmovie', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.tvmovie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('war', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.war')),
                ('western', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.western')),
            ],
        ),
    ]
