# Generated by Django 3.2.3 on 2021-09-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0067_remove_practise_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Practise',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='fantasy',
        ),
        migrations.RemoveField(
            model_name='like',
            name='fantasy',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='fantasy',
        ),
        migrations.DeleteModel(
            name='Fantasy',
        ),
    ]
