# Generated by Django 3.2.3 on 2021-09-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0069_fantasy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fantasy',
        ),
    ]
