# Generated by Django 3.2.3 on 2021-09-22 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0070_delete_fantasy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fantasy',
            fields=[
                ('genres', models.CharField(blank=True, max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
