# Generated by Django 3.2.3 on 2021-09-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0073_moviereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='moviereview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='like',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='movie',
        ),
        migrations.DeleteModel(
            name='MovieList',
        ),
        migrations.DeleteModel(
            name='MovieReview',
        ),
    ]
