# Generated by Django 3.2.3 on 2021-09-27 15:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieapp', '0074_auto_20210927_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('genres', models.CharField(blank='True', max_length=300)),
                ('id', models.CharField(max_length=300, primary_key='True', serialize=False)),
                ('original_title', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveIntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.movielist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='like',
            name='action',
        ),
        migrations.RemoveField(
            model_name='like',
            name='adventure',
        ),
        migrations.RemoveField(
            model_name='like',
            name='animation',
        ),
        migrations.RemoveField(
            model_name='like',
            name='comedy',
        ),
        migrations.RemoveField(
            model_name='like',
            name='crime',
        ),
        migrations.RemoveField(
            model_name='like',
            name='documentary',
        ),
        migrations.RemoveField(
            model_name='like',
            name='drama',
        ),
        migrations.RemoveField(
            model_name='like',
            name='family',
        ),
        migrations.RemoveField(
            model_name='like',
            name='foreign',
        ),
        migrations.RemoveField(
            model_name='like',
            name='history',
        ),
        migrations.RemoveField(
            model_name='like',
            name='horror',
        ),
        migrations.RemoveField(
            model_name='like',
            name='music',
        ),
        migrations.RemoveField(
            model_name='like',
            name='mystery',
        ),
        migrations.RemoveField(
            model_name='like',
            name='popularmovies',
        ),
        migrations.RemoveField(
            model_name='like',
            name='romance',
        ),
        migrations.RemoveField(
            model_name='like',
            name='sciencefiction',
        ),
        migrations.RemoveField(
            model_name='like',
            name='thriller',
        ),
        migrations.RemoveField(
            model_name='like',
            name='tvmovie',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='war',
        ),
        migrations.RemoveField(
            model_name='like',
            name='western',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='action',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='adventure',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='animation',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='comedy',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='crime',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='documentary',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='drama',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='family',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='foreign',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='history',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='horror',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='music',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='mystery',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='popularmovies',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='romance',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='sciencefiction',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='thriller',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='tvmovie',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='war',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='western',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
