# Generated by Django 3.2.3 on 2021-10-01 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieapp', '0076_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatingMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.movielist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.users')),
            ],
        ),
    ]
